# metadata
title: Chee Jun Hong
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. You'll find all of your configurations in your _config.yml file.
  all of the images are stored in /assets/images folder. Change them according to your needs.
  Go to the portfolio section and see the projects. You'll get the tutorial for projects on one of the project.
tagline: A human being
baseurl: ""
url: ""

# edit it to meet your needs
github: pipipapipo
linkedin: ""
email: "junhong.chee@pipipapipo.com"
location: singapore


# no need to touch this
sass:
  style: compressed

collections:
  projects:
    output: true
    permalink: /projects/:name
