# metadata
title: Chee Jun Hong
description: >-
 A strategic MBA candidate, a highly analytical Certified ScrumMaster, a results-driven Business analyst who strongly believe in attention to detail, lean management, work efficiency, automation, continuous improvement, and dedication to meet and exceed all goals.e.
  all of the images are stored in /assets/images folder. Change them according to your needs.
  Go to the portfolio section and see the projects. You'll get the tutorial for projects on one of the project.
tagline: A human being
baseurl: ""
url: ""

# edit it to meet your needs
github: pipipapipo
linkedin: "www.linkedin.com/in/jun-hong-chee"
email: "junhong.chee@pipipapipo.com"
location: singapore


# no need to touch this
sass:
  style: compressed

collections:
  projects:
    output: true
    permalink: /projects/:name
